language: c

compiler:
  - clang
  - gcc

script:
  - sh ./autogen.sh
  - ./configure
  - make distcheck

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#pkgconf"
    on_success: change
    on_failure: always
